spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lgr?useSSL=false&serverTimezone=UTC
#    url: jdbc:oracle:thin:@//192.168.1.100:1521/orcl
    username: root
    password: x5
server:
  port: 9010